print("Welcome to Bill and Tip Calculator: ")
bill = input("what is the total bill: $ ")
#print(bill)
tip = input("how much would you tip: 10,12 or15 (Percentage) ")
total_bill = int(bill) + (int(bill) * int(tip) / 100 ) 
# print(total_bill)
# print(type(total_bill))
people = input("How Many people to split the bill: ") 
contri = int(total_bill) / int(people)
contri2 = round(contri, 2)
print("each person has to pay  " + str(contri2))